# 监听 main 分支
on:
  push:
    branches:
      - test

# action 名称
name: Contributes

jobs:
  # 任务
  contrib-readme-en-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    if: github.repository == 'hellof2e/quark-core' 
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTORS_TOKEN }}
